# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dashboardxynvrZg.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        if not Dashboard.objectName():
            Dashboard.setObjectName(u"Dashboard")
        Dashboard.resize(800, 600)
        self.centralwidget = QWidget(Dashboard)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 20, 171, 31))
        font = QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(300, 20, 171, 31))
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(550, 20, 181, 31))
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 130, 151, 41))
        font1 = QFont()
        font1.setPointSize(18)
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(310, 130, 151, 41))
        self.label_5.setFont(font1)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(580, 130, 151, 41))
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.stockOne = QLabel(self.frame)
        self.stockOne.setObjectName(u"stockOne")
        self.stockOne.setGeometry(QRect(60, 250, 131, 41))
        font2 = QFont()
        font2.setPointSize(15)
        font2.setBold(False)
        self.stockOne.setFont(font2)
        self.stockOne.setAlignment(Qt.AlignCenter)
        self.stockTwo = QLabel(self.frame)
        self.stockTwo.setObjectName(u"stockTwo")
        self.stockTwo.setGeometry(QRect(230, 250, 141, 41))
        self.stockTwo.setFont(font2)
        self.stockTwo.setAlignment(Qt.AlignCenter)
        self.stockThree = QLabel(self.frame)
        self.stockThree.setObjectName(u"stockThree")
        self.stockThree.setGeometry(QRect(430, 250, 131, 41))
        self.stockThree.setFont(font2)
        self.stockThree.setAlignment(Qt.AlignCenter)
        self.stockFour = QLabel(self.frame)
        self.stockFour.setObjectName(u"stockFour")
        self.stockFour.setGeometry(QRect(610, 250, 131, 41))
        self.stockFour.setFont(font2)
        self.stockFour.setAlignment(Qt.AlignCenter)
        self.startButton = QPushButton(self.frame)
        self.startButton.setObjectName(u"startButton")
        self.startButton.setGeometry(QRect(100, 520, 231, 41))
        self.stopButton = QPushButton(self.frame)
        self.stopButton.setObjectName(u"stopButton")
        self.stopButton.setGeometry(QRect(470, 520, 231, 41))
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(60, 60, 171, 31))
        self.label_11.setFont(font)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.frame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(300, 60, 171, 31))
        self.label_12.setFont(font)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.frame)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(550, 60, 181, 31))
        self.label_13.setFont(font)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.reserveText = QTextEdit(self.frame)
        self.reserveText.setObjectName(u"reserveText")
        self.reserveText.setGeometry(QRect(70, 170, 171, 31))
        font3 = QFont()
        self.reserveText.setFont(font3)
        self.reserveText.setLayoutDirection(Qt.LeftToRight)
        self.reserveText.setStyleSheet(u"")
        self.tradeText = QTextEdit(self.frame)
        self.tradeText.setObjectName(u"tradeText")
        self.tradeText.setGeometry(QRect(300, 170, 171, 31))
        self.riskText = QTextEdit(self.frame)
        self.riskText.setObjectName(u"riskText")
        self.riskText.setGeometry(QRect(560, 170, 171, 31))
        self.stockOneText = QTextEdit(self.frame)
        self.stockOneText.setObjectName(u"stockOneText")
        self.stockOneText.setGeometry(QRect(60, 290, 131, 31))
        self.stockTwoText = QTextEdit(self.frame)
        self.stockTwoText.setObjectName(u"stockTwoText")
        self.stockTwoText.setGeometry(QRect(240, 290, 131, 31))
        self.stockThreeText = QTextEdit(self.frame)
        self.stockThreeText.setObjectName(u"stockThreeText")
        self.stockThreeText.setGeometry(QRect(430, 290, 131, 31))
        self.stockFourText = QTextEdit(self.frame)
        self.stockFourText.setObjectName(u"stockFourText")
        self.stockFourText.setGeometry(QRect(610, 290, 131, 31))
        self.graphicsView = QGraphicsView(self.frame)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(20, 380, 741, 101))

        self.verticalLayout.addWidget(self.frame)

        Dashboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dashboard)

        QMetaObject.connectSlotsByName(Dashboard)
    # setupUi

    def retranslateUi(self, Dashboard):
        Dashboard.setWindowTitle(QCoreApplication.translate("Dashboard", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("Dashboard", u"PREVIOUS DAY", None))
        self.label_2.setText(QCoreApplication.translate("Dashboard", u"PREVIOUS WEEK", None))
        self.label_3.setText(QCoreApplication.translate("Dashboard", u"PREVIOUS MONTH", None))
        self.label_4.setText(QCoreApplication.translate("Dashboard", u"RESERVE", None))
        self.label_5.setText(QCoreApplication.translate("Dashboard", u"TRADE", None))
        self.label_6.setText(QCoreApplication.translate("Dashboard", u"RISK %", None))
        self.stockOne.setText(QCoreApplication.translate("Dashboard", u"STOCK 1", None))
        self.stockTwo.setText(QCoreApplication.translate("Dashboard", u"STOCK 2", None))
        self.stockThree.setText(QCoreApplication.translate("Dashboard", u"STOCK 3", None))
        self.stockFour.setText(QCoreApplication.translate("Dashboard", u"STOCK 4", None))
        self.startButton.setText(QCoreApplication.translate("Dashboard", u"START", None))
        self.stopButton.setText(QCoreApplication.translate("Dashboard", u"STOP", None))
        self.label_11.setText(QCoreApplication.translate("Dashboard", u"$ 100", None))
        self.label_12.setText(QCoreApplication.translate("Dashboard", u"$ 1000", None))
        self.label_13.setText(QCoreApplication.translate("Dashboard", u"$ 4000", None))
    # retranslateUi

